resources:
  - name: sample_python
    type: gitRepo
    repoPath: manishas/node_app_jfrog
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_1
    setup:
      runtime: host
    steps:
      - name: test_bash_step
        type: bash
        setup:
          runtime: host
        triggeredBy:
          resources:
            - sample_python 
        execution:
          onExecute:
            - echo "First run....."
            - echo "executing step_A..."
